"""initial: documents and abstracts

Revision ID: 6627483126b5
Revises:
Create Date: 2026-05-02 10:45:48.306766

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6627483126b5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openalex_id", sa.String(length=50), nullable=True),
        sa.Column("doi", sa.String(length=200), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.JSON(), nullable=False),
        sa.Column("venue", sa.String(length=500), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("primary_topic", sa.String(length=100), nullable=False),
        sa.Column("extra_topics", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("is_oa", sa.Boolean(), nullable=False),
        sa.Column("cited_by_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "METADATA_ONLY",
                "FULLTEXT_PENDING",
                "FULLTEXT_INDEXED",
                "FAILED",
                name="indexstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
        sa.UniqueConstraint("openalex_id"),
    )
    op.create_index(
        op.f("ix_documents_primary_topic"), "documents", ["primary_topic"], unique=False
    )
    op.create_index(op.f("ix_documents_year"), "documents", ["year"], unique=False)
    op.create_table(
        "abstracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("qdrant_point_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_index(op.f("ix_abstracts_document_id"), "abstracts", ["document_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_abstracts_document_id"), table_name="abstracts")
    op.drop_table("abstracts")
    op.drop_index(op.f("ix_documents_year"), table_name="documents")
    op.drop_index(op.f("ix_documents_primary_topic"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
