"""Generate a Markdown inventory of every document in the corpus.

Sprint 5d follow-up: ad-hoc reporting tool to answer "what's actually in
the knowledge base right now?" beyond the headline numbers the meta
handler returns. Writes to ``evals/v1/corpus-inventory-<date>.md`` and
prints a one-paragraph summary to stdout.

Usage:
    python scripts/corpus_stats.py
"""

from __future__ import annotations

import sys
from collections import Counter
from datetime import date
from pathlib import Path

from sqlalchemy import func

from neblab_rag.db.engine import get_session
from neblab_rag.db.models import Chunk, Document, IndexStatus

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "evals" / "v1"


def main() -> None:
    today = date.today().isoformat()
    out_path = OUTPUT_DIR / f"corpus-inventory-{today}.md"
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    with get_session() as session:
        total_docs = session.query(Document).count()
        total_chunks = session.query(Chunk).count()

        status_rows = (
            session.query(Document.status, func.count(Document.id))
            .group_by(Document.status)
            .all()
        )
        lang_rows = (
            session.query(Document.language, func.count(Document.id))
            .group_by(Document.language)
            .order_by(func.count(Document.id).desc())
            .all()
        )
        topic_rows = (
            session.query(Document.primary_topic, func.count(Document.id))
            .group_by(Document.primary_topic)
            .order_by(func.count(Document.id).desc())
            .all()
        )
        year_rows = (
            session.query(Document.year, func.count(Document.id))
            .group_by(Document.year)
            .order_by(Document.year.desc().nulls_last())
            .all()
        )
        venue_rows = (
            session.query(Document.venue, func.count(Document.id))
            .filter(Document.venue.isnot(None))
            .group_by(Document.venue)
            .order_by(func.count(Document.id).desc())
            .limit(20)
            .all()
        )

        # Whole-corpus listing: id, title, language, year, topic, status,
        # openalex_id. Loaded into memory because writing as one block is
        # fine for ~2k rows.
        docs = (
            session.query(
                Document.id,
                Document.title,
                Document.language,
                Document.year,
                Document.primary_topic,
                Document.status,
                Document.openalex_id,
            )
            .order_by(
                Document.primary_topic,
                Document.language,
                Document.year.desc().nulls_last(),
                Document.id,
            )
            .all()
        )

    # --- breakdown summaries ---
    status_summary = "\n".join(
        f"- **{status.value}**: {count}" for status, count in sorted(status_rows)
    )
    lang_summary = "\n".join(
        f"- **{lang or 'unknown'}**: {count}" for lang, count in lang_rows
    )
    topic_summary = "\n".join(
        f"- **{topic}**: {count}" for topic, count in topic_rows
    )

    # decade buckets are friendlier than per-year for a 100+-year corpus
    decade_counter: Counter[str] = Counter()
    null_year_count = 0
    for year, count in year_rows:
        if year is None:
            null_year_count += count
            continue
        decade_counter[f"{(year // 10) * 10}s"] += count
    decade_summary = "\n".join(
        f"- **{decade}**: {count}"
        for decade, count in sorted(decade_counter.items(), reverse=True)
    )
    if null_year_count:
        decade_summary += f"\n- **unknown year**: {null_year_count}"

    venue_summary = "\n".join(
        f"- {venue} ({count})" for venue, count in venue_rows
    )

    # --- full inventory table ---
    listing_lines = [
        "| # | Title | Lang | Year | Topic | Status | OpenAlex |",
        "|---|---|---|---|---|---|---|",
    ]
    for i, (
        doc_id,
        title,
        language,
        year,
        topic,
        status,
        openalex_id,
    ) in enumerate(docs, 1):
        clean_title = (title or "").replace("|", "/").replace("\n", " ").strip()
        if len(clean_title) > 140:
            clean_title = clean_title[:137] + "…"
        listing_lines.append(
            f"| {i} | {clean_title} | {language or '—'} | {year or '—'} | "
            f"{topic} | {status.value} | "
            f"{openalex_id or '—'} |"
        )
    listing_block = "\n".join(listing_lines)

    body = f"""# NEBLab corpus inventory · {today}

Auto-generated by `scripts/corpus_stats.py`. Source of truth: Postgres
`documents` + `chunks` tables.

## 总览

- 总文献数：**{total_docs}** 篇
- 总 chunks：**{total_chunks}** 个

## 按 status 分布

{status_summary}

## 按语种分布

{lang_summary}

## 按主题分布（primary_topic）

{topic_summary}

## 按年代分布

{decade_summary}

## 高频期刊 / 来源（top 20）

{venue_summary if venue_summary else "(无数据)"}

## 全部文献清单

按 (主题 → 语种 → 年份倒序) 排列。

{listing_block}
"""

    out_path.write_text(body, encoding="utf-8")

    print(
        f"wrote {out_path.relative_to(OUTPUT_DIR.parent.parent)} "
        f"({total_docs} docs, {total_chunks} chunks)",
        file=sys.stderr,
    )
    print()
    print(f"## 当前 NEBLab 语料库（{today}）")
    print(f"- 总文献：{total_docs} 篇 / 总 chunks：{total_chunks}")
    print(f"- 主题：{', '.join(t for t, _ in topic_rows[:5])}")
    print(f"- 语种：{', '.join(f'{l or 'unknown'}={c}' for l, c in lang_rows)}")
    print()
    print(f"完整清单写入：{out_path}")


if __name__ == "__main__":
    main()
